// This file is automatically generated after creating a new model with sequelize CLI
// I customized createdAt and UpdatedAt in order to make them return formatted dates

// Call moment js for manipulating format date
const moment = require("moment");
("use strict");
const { Model } = require("sequelize");
module.exports = (sequelize, DataTypes) => {
  class BoardScore extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
    static associate(models) {
      // define association here
    }
  }
  BoardScore.init(
    {
      score: DataTypes.INTEGER,
      // Configure sequelize model, for formating the date before send back
      createdAt: {
        type: DataTypes.DATE,
        get() {
          return moment(this.getDataValue("createdAt"))
            .locale("fr")
            .format("DD MMM YY");
        },
      },
      updatedAt: {
        type: DataTypes.DATE,
        get() {
          return moment(this.getDataValue("updatedAt"))
            .locale("fr")
            .format("DD MMM YY");
        },
      },
    },
    {
      sequelize,
      modelName: "BoardScore",
    }
  );
  return BoardScore;
};
